---
- name: Build Exploratory Analysis Server
  command: docker build -t core_analysis ../docker/analysis

- name: Exploratory Analysis container
  docker:
    domainname: "{{domain_name}}"
    hostname: analysis
    name: analysis
    image: core_analysis
    net: virtual_core
    state: reloaded
    ports: ["7443:443"]
    volumes:
      - "{{ analysis_dir }}/home:/home"
      - "{{ software_dir }}:/vcore/software"
