---
- name: Build User Server
  command: docker build -t core_user_server ../../docker/user_server

- name: User Server container
  docker:
    name: "{{ item.name }}"
    domainname: "{{ domain_name }}"
    hostname: "{{ item.host_name }}"
    image: core_user_server
    net: virtual_core
    state: reloaded
    ports: "{{ item.ports }}"
    volumes: "{{ default_volumes + item.volumes }}"
  with_items: "{{ user_servers }}"
