---
- name: Build User Server
  command: docker build -t core_user_server ../docker/user-server

- name: User Server container
  docker:
    name: user_server
    domainname: "{{domain_name}}"
    hostname: user_server
    image: core_user_server
    net: virtual_core
    state: reloaded
    ports: ["2222:22"]
    volumes:
      - "{{ home_dir }}:/home"
      - "{{ software_dir }}:/vcore/software"
