---
- name: Build Cluster Server
  command: docker build -t core_compute_server ../../docker/compute-server

- name: Cluster Server container
  docker:
    domainname: "{{domain_name}}"
    hostname: compute_server
    name: compute_server
    image: core_compute_server
    priviledged: yes
    net: virtual_core
    state: reloaded
    volumes:
      - "{{ software_dir }}:/vcore/software"
