---
- name: Build LDAP server
  docker_image:
    path: ../../docker/ldap
    name: localhost:5000/ldap
    push: yes

- name: Build phpLDAPadmin server
  docker_image:
    path: ../../docker/phpldapadmin
    name: localhost:5000/phpldapadmin
    push: yes

- name: LDAP container
  docker_service:
    domainname: "{{domain_name}}"
    hostname: ldap
    name: ldap
    image: core_ldap
    net: virtual_core
    state: reloaded
    ports: ["636:636", "389:389"]
    volumes:
      - "{{ ldap_dir }}/var/lib/openldap:/var/lib/openldap"
      - "{{ ldap_dir }}/var/run/openldap:/var/run/openldap"
      - "{{ ldap_dir }}/etc/openldap:/etc/openldap"
      - "{{ ldap_dir }}/var/log:/var/log"

- name: phpLDAPadmin container
  docker_service:
    domainname: "{{domain_name}}"
    hostname: phpldapadmin
    name: phpldapadmin
    image: core_phpldapadmin
    net: virtual_core
    state: reloaded
    ports: ["8636:443"]
    volumes:
      - "{{ phpldapadmin_dir }}/var/log:/var/log"

