---
- name: Build LDAP server
  command: docker build -t core_ldap ../../docker/ldap

- name: Build phpLDAPadmin server
  command: docker build -t core_phpldapadmin ../../docker/phpldapadmin

- name: LDAP container
  docker:
    domainname: "{{domain_name}}"
    hostname: ldap
    name: ldap
    image: core_ldap
    net: virtual_core
    state: reloaded
    ports: ["636:636", "389:389"]
    volumes:
      - "{{ ldap_dir }}/var/lib/openldap:/var/lib/openldap"
      - "{{ ldap_dir }}/var/run/openldap:/var/run/openldap"
      - "{{ ldap_dir }}/etc/openldap:/etc/openldap"
      - "{{ ldap_dir }}/var/log:/var/log"

- name: phpLDAPadmin container
  docker:
    domainname: "{{domain_name}}"
    hostname: phpldapadmin
    name: phpldapadmin
    image: core_phpldapadmin
    net: virtual_core
    state: reloaded
    ports: ["8636:443"]
    volumes:
      - "{{ phpldapadmin_dir }}/var/log:/var/log"

