---
- name: Build Software builder
  command: docker build -t core_software ../docker/software

- name: Create software 
  docker:
    name: software
    domainname: "{{domain_name}}"
    hostname: software
    image: core_software
    state: reloaded
    volumes:
      - "{{ software_dir }}:/vcore/software"

